---
title: Экспедиция камергера Н. П. Резанова с инспекцией в Русскую Америку
---

sequenceDiagram

    actor Н. П. Резанов

    participant Кронштадт    
    participant Петропавловск    
    participant Нагасаки
    participant Ново-Архангельск
    participant Сан-Франциско
    participant Охотск
    participant Красноярск
    actor Н. А. Хвостов и Г. И. Давыдов
    participant Сахалин
    
    activate Н. П. Резанов

    Н. П. Резанов->>Кронштадт: 26 июля 1803 г.    
    Кронштадт->>Петропавловск: 15 июля 1804 г. 

    Петропавловск->>Нагасаки: 26 сентября 1804 г.   
    Нагасаки->>Петропавловск: 23 марта 1805 г.

    Петропавловск->>Ново-Архангельск: лето-осень 1805 г.
    Ново-Архангельск->>Сан-Франциско: март 1806 г.
    Сан-Франциско->>Ново-Архангельск: 11 июня 1806 г.
    Ново-Архангельск->>Охотск: сентябрь 1806 г.

    activate Н. А. Хвостов и Г. И. Давыдов

    Н. П. Резанов-->>Н. А. Хвостов и Г. И. Давыдов: инструкции о нападении на Сахалин
    Н. А. Хвостов и Г. И. Давыдов->>Сахалин: набег в октябре 1806 г.

    Охотск->>Красноярск: смерть Резанова 1 марта 1807 г.

    deactivate Н. П. Резанов

    Сахалин->>Охотск: прекращение пиратства 16 июля 1807 г.

    deactivate Н. А. Хвостов и Г. И. Давыдов

    