---
title: Экспедиция камергена Н.П. Резанова с инспекцией в Русскую Америку
---
sequenceDiagram

    actor И. Ф. Крузенштерн
    actor Н. П. Резанов
    actor Н. А. Хвостов и Г. И. Давыдов

    participant Посольство в Японию
    participant Кронштадт    
    participant Петропавловск    
    participant Нагасаки
    participant Ново-Архангельск
    participant Сан-Франциско
    participant Охотск
    participant Красноярск
    participant Сахалин
    
    activate Н. П. Резанов
    activate И. Ф. Крузенштерн
    activate Посольство в Японию

    И. Ф. Крузенштерн->>Посольство в Японию: 26 июля 1803 г.
    Н. П. Резанов->>Посольство в Японию: 26 июля 1803 г.
    Посольство в Японию->>Кронштадт: 26 июля 1803 г.    
    Кронштадт->>Петропавловск: 15 июля 1804 г. 

    deactivate И. Ф. Крузенштерн

    Петропавловск->>Нагасаки: 26 сентября 1804 г.   
    Нагасаки->>Петропавловск: убыл 23 марта 1805 г.

    Петропавловск->>Ново-Архангельск: лето-осень 1805 г.
    Ново-Архангельск->>Сан-Франциско: март 1806 г.
    Сан-Франциско->>Ново-Архангельск: 11 июня 1806 г.
    Ново-Архангельск->>Охотск: сентябрь 1806 г.

    activate Н. А. Хвостов и Г. И. Давыдов

    Н. П. Резанов->>Н. А. Хвостов и Г. И. Давыдов: инструкции о нападении на Сахалин
    Н. А. Хвостов и Г. И. Давыдов->>Сахалин: набег в октябре 1806 г.

    Охотск->>Красноярск: смерть Резанова 1 марта 1807 г.

    deactivate Н. П. Резанов

    Сахалин->>Охотск: прекращение пиратства 16 июля 1807 г.

    deactivate Н. А. Хвостов и Г. И. Давыдов

    