---
title: Участие Н.П. Резанова в экспедиции И. Ф. Крузенштерна
---
sequenceDiagram


    participant Экспедиция

    participant Кронштадт    
    participant Петропавловск    
    actor Крузенштерн
    actor Резанов
    participant Нагасаки
    participant Аляска

    Экспедиция->>Кронштадт: 26 июля 1803 г., отправление   
    Кронштадт->>Петропавловск: 15 июля 1804 г., прибытие 

    Резанов->>Нагасаки: 26 сентября 1804 г.   
    Нагасаки->>Петропавловск: Резанов, убыл 23 марта 1805 г.

    Крузенштерн->>Аляска: лето 1804 г.
