---
title: Императоры и канцлеры Российской империи в XIX в.
description: За всю историю Российской империи канцлеров было меньше, чем царствующих монархов. Как правило (за исключением периода Наполеоновских войн), в государстве был только один канцлер, а между смертью предыдущего канцлера и получением чина новым нередко проходили годы. Последние 50 лет (с назначения Горчакова) существования монархии этот чин никому не присваивался, хотя формально отменён не был. Последние 35 лет (со смерти Горчакова) Российская империя прожила без канцлера.
---

timeline


    section Александр I
        Воронцов Александр Романович (1802-1805) : Сближение с Англией и Австрией, граф Римской империи
        Румянцев Николай Петрович (1809-1826) : Реформы коммерции, Улучшение судоходства, Посольство в Пекин, Сближение с Наполеоном, Усиление Русской Америки
    section Николай I
        Кочубей, Виктор Павлович (1834) : Негласный комитет, Сибирский комитет, Попечительский совет, Балы Кочубеев
        Нессельроде Карл Васильевич (1844-1862) : Венгерское восстание, Крымская война, Замирение с Китаем и Японией, Развитие железных дорог
    section Александр II
        Горчаков Александр Михайлович (1867-1883) : Парижский мир, Последствия Крымской войны, Сближение с Италией, Польский вопрос, Австро-прусская война, Усиление Германии, Тройственный союз, Русско-турецкая война, Берлинский конгресс
