---
title: Императоры и канцлеры Российской империи в XVIII в.
description: Следует учитывать, что некоторые канцлеры занимали свои должности при нескольких императоах, а иногда должность канцлера и вовсе несколько лет оставалась вакантной.
---

timeline

    section Петр I
        Головин Фёдор Алексеевич (1699—1706): Нерченский договор, Великое посольство, Сибирский наместник, Азовский поход, Навигацкая школа, Битва при Нарве, Государева дорого, осада Ниеншанца, осада Нотеборга, граф Римской империи
    section Екатерина I,  Анна Иоанновна
        Головкин Гавриил Иванович (1706—1734) : Стольник царевича Петра,  Царская мастерская палата, дела Польши и Украины, просил Петра стать императором, Верховный тайный совет, опекун Петра II, вражда с Долгоруковыми, граф Римской империи
    section Иван VI, Елизавета Петровна
        Черкасский Алексей Михайлович (1740-1742) : Служба в Тобольске, обер-комиссар Петербурга, губернатор Сибири, противник верховников, торговля с Хивой и Бухарой, торговый договор с Англией, проект союза России с Францией, сторонник Бирона, трактат о союзе с Пруссией, конвенция с Данией, разрыв с Францией, сближение с Англией
        Бестужев-Рюмин Алексей Петрович (1744-1758) : Резидент Петра I в Копенгагене, Интриги против Меншикова, Кабинет-министр, в Шлиссельбургской крепости, Разрыв с Францией, Мир со Швецией, Дело Лопухиной и союз с Воронцовым, получил в собственность казённые арендные земли в Лифляндии, Союз с Австрией, Иностранные субсидии, Следствие и ссылка, граф Римской империи
    section Петр III, Екатерина II
        Воронцов Михаил Илларионович (1758-1765) : арестовал Анну Леопольдовну, союз с Австрией против Турции, был весьма привержен Петру, По мнению ряда иностранных наблюдателей, Воронцов был поставлен во главе ведомства иностранных дел как ширма, прикрывающая братьев Шуваловых, граф Римской империи       
    section Екатерина II, Павел I
        Остерман Иван Андреевич (1796-1797) : Посол в Швеции, Глава русской дипломатии, торговый трактат между Россией и Портой (1783), трактат с Францией о дружбе, торговле и мореплавании (1786), такой же трактат между Россией и Англией, союзный и оборонительный договор между российской императрицей и английским королём (1795), конвенция об окончательном разделе Польши
    section Павел I
        Безбородко Александр Андреевич (1797-1799) : «Правая рука» Румянцева-Задунайского, заключении морской декларации 28 февраля 1780 г. и в ряде других трактатов (1780-83) о морском нейтралитете, также в заключении оборонительных союзных договоров России с Австрией, Пруссией (1792) и Великобританией (1794), в третьем разделе Польши (1795), граф Римской империи
